In [3]:
import torch
import numpy as np

Task 1.1: Tạo Tensor

In [4]:
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")
# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")
# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")


x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")
# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.3109, 0.9433],
        [0.6476, 0.9094]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


Task 1.2: Các phép toán trên Tensor

In [ ]:
print(x_data + x_data)
print(x_data*5)
print(x_data * x_data.T)
print(x_data @ x_data)

tensor([[2, 4],
        [6, 8]])
tensor([[ 5, 10],
        [15, 20]])
tensor([[ 1,  6],
        [ 6, 16]])
tensor([[ 7, 10],
        [15, 22]])


In [7]:
#Lấy ra hàng đầu tiên
print(x_data[0])

#Lấy ra cột thứ 2
print(x_data[:, 1])

#Lấy ra giá trị hàng 2 cột 2:
print(x_data[1,1])

tensor([1, 2])
tensor([2, 4])
tensor(4)


Task 1.4: Thay đổi hình dạng Tensor

In [17]:
rand_tensor = torch.rand([4,4])
print(rand_tensor.shape)
rand_tensor = torch.reshape(rand_tensor, [16,1])
print(rand_tensor.shape)

torch.Size([4, 4])
torch.Size([16, 1])


Phần 2: Tự động tính Đạo hàm với autograd

Task 2.1: Thực hành với autograd

In [21]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")
# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")
# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")
# Thực hiện thêm các phép toán
z = y * y * 3
# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))
# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

z.backward()
print(x.grad)

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x00000293B2D64310>
Đạo hàm của z theo x: tensor([18.])


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

Xảy ra lỗi khi gọi z.backward lần 2 mà không có retain_graph=True do graph không lưu lại các giá trị trung gian như z, y sau khi gọi .backward()

Phần 3: Xây dựng Mô hình đầu tiên với torch.nn

Task 3.1: Lớp nn.Linear

In [29]:
#Khởi tạo một lớp Linear biến đổi từ 5 chiều thành 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

#Tạo một Tensor đầu vào mẫu
input_tensor = torch.randn(3,5)

#Truyền đầu vào qua lớp Linear
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 0.0446,  0.4521],
        [-1.2552,  0.6315],
        [ 1.1494, -0.7613]], grad_fn=<AddmmBackward0>)


Task 3.2: Lớp nn.Embedding

In [31]:
#Khởi tạo lớp Embeđing cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

#Tạo 1 tensor đầu vào chứa các chỉ só của các từ(một câu)
#Các chỉ số phải nhỏ hơn 1
input_indices = torch.LongTensor([1,5,0,8])

#lấy ra các vector Embedding tương ứng
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.5268, -0.8154,  1.0057],
        [ 1.5233, -0.3772,  0.6424],
        [ 0.5559, -0.5783, -0.3104],
        [-0.0293, -0.8628, -1.7664]], grad_fn=<EmbeddingBackward0>)


In [34]:
from torch import nn
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output

In [35]:
# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
